.TH BYTHON 1
.SH NAME
by2py \- Translate bython files to python
.SH SYNOPSIS
.B by2py
[\fIFLAGS\fR]
.IR scriptfile
.SH DESCRIPTION
.B by2py
is an alias for 'bython -c'. For more information, look up the manual for bython(1).
.SH SEE ALSO
bython(1)
.SH AUTHOR
Mathias Lohne 2017, 
Tristan Pepin 2017
.SH LICENSE
This program is licensed under the MIT license. See [1] for details. TL;DR: Do whatever you want as long as you include the original copyright and license notice.
.TP
[1]
https://github.com/mathialo/bython/blob/master/LICENSE



