.TH BYTHON 1
.SH NAME
py2by \- Translate python files to bython
.SH SYNOPSIS
.B py2by
[\fIFLAGS\fR]
.IR scriptfile
.SH DESCRIPTION
.B py2by
is a program that translates regular python scripts to bython
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Show help message and exit.
.TP
.BR \-v ", " \-\-version
Show version number and exit.
.TP
.BR \-o ", " \-\-output
Specify the name of output file.
.SH SEE ALSO
bython(1)
.SH AUTHOR
Mathias Lohne 2018, 
Tristan Pepin 2018
.SH LICENSE
This program is licensed under the MIT license. See [1] for details. TL;DR: Do whatever you want as long as you include the original copyright and license notice.
.TP
[1]
https://github.com/mathialo/bython/blob/master/LICENSE



